language: node_js
node_js:
  - "8"
cache: yarn
branches:
  only:
    - master
before_script:
  - "yarn global add firebase-tools"
  - "yarn global add gatsby"
  - "yarn global add eslint"
script:
  - "yarn build"
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN