language: node_js
node_js:
  - "8"
cache: yarn
branches:
  only:
    - master
before_install:
  - "yarn global add firebase-tools"
  - "yarn global add gatsby"
install:
  - "yarn build"
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN